<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Default.aspx.vb" Inherits="adminService._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>PURCHASE SCORE</title>
    <style type="text/css">
        #form1
        {
            text-align: center;
        }
    </style>
    
    <style type="text/css">
tr.hoverColorWrite:hover 
{
	
	background-color :White ;
	color: red;	
	
}

tr.hoverColor:hover 
{
	background: #FFFFCC;
	background: #eeeeee;
		
	
}
a:hover {
	color: #FF6600; LEFT: 1px; position:relative; TOP: 1px  
}        
        .style1
        {
            font-size: small;
        }
        .style4
        {
            width: 216px;
            height: 31px;
        }
        .style8
        {
            width: 400px;
        }
        .style10
        {
            height: 35px;
        }
        .style11
        {
            height: 31px;
        }
        .style12
        {
            height: 5px;
        }
        .style13
        {
            color: #666666;
        }
        .style14
        {
            color: #3399FF;
            font-size: small;
        }
        .style15
        {
            color: #0066FF;
        }
        
        
        INPUT {
	BORDER-BOTTOM: #eae8e8 1px solid; BORDER-LEFT: #eae8e8 1px solid; PADDING-BOTTOM: 0.32em; PADDING-LEFT: 0.15em;  PADDING-RIGHT: 0.15em; FONT: normal 0.95em Tahoma; BACKGROUND: #f2f2f2; BORDER-TOP: #eae8e8 1px solid; BORDER-RIGHT: #eae8e8 1px solid; PADDING-TOP: 0.32em; -moz-border-radius: 0.4em; -khtml-border-radius: 0.4em; font-size:13px;border-radius: .5em;color:#333333;box-shadow: 0 0 3px #eae8e8;
} 
        .style16
        {
            width: 216px;
            height: 35px;
            color: #999999;
        }
        .style17
        {
            color: #FF66FF;
            font-weight: bold;
        }
    </style>
    
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <center>
        <asp:Panel ID="Panel_login" runat="server" Width="960px" Height="713px">
            <center><font face="MS Sans Serif"></font>&#160;<br />
                <TABLE ID="Table2" align="center" bgcolor="White" border="0" cellPadding="1" 
                    cellSpacing="1" 
                    
                    style="border: 1px solid #808080; WIDTH: 509px; HEIGHT: 61px; background-color: #F3F3F3;">
                    <tr>
                        <td align="right" class="style15" colspan="2" 
                            style="text-align: center; background-color: #99CCFF;">
                            <b>PURCHASE SATISFACATION</b></td>
                    </tr>
                    <tr>
                        <td align="right" class="style4">
                        </td>
                        <td align="left" class="style11">
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="style16">
                            User :</td>
                        <td align="left" class="style10" style="vertical-align: bottom">
                            <font face="MS Sans Serif">&nbsp; </font>
                            <asp:TextBox ID="txtUser" runat="server" BackColor="#FFFFCC" Width="85px"></asp:TextBox>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="style16">
                            Password :</td>
                        <td align="left" class="style10" style="vertical-align: bottom">
                            <font face="MS Sans Serif">&nbsp; </font>
                            <asp:TextBox ID="txtPwd" runat="server" BackColor="#FFFFCC" TextMode="Password" 
                                Width="85px"></asp:TextBox>
                            &nbsp;</td>
                    </tr>
                    <tr>
                        <td align="right" colspan="2">
                            &nbsp;</td>
                    </tr>
                    <tr>
                        <td align="right" colspan="2">
                            <center>
                                <font face="MS Sans Serif"><span class="style14">** ใช้ User/password 
                                ที่ท่านใช้เข้าเครื่องทุกเช้าครับ!! **</span></font></center>
                        </td>
                    </tr>
                    <tr>
                        <td align="right" colspan="2" style="text-align: center;">
                            &nbsp;<asp:Button ID="button_Login" runat="server" style="font-weight: 700" 
                                Text="Login" Width="66px" BackColor="#3399FF" ForeColor="White" />
                            &nbsp;<br />
                            <span class="style17">** สำหรับ Purchase เท่านั้น**</span><br />
                        </td>
                    </tr>
                    <tr>
                        <td align="right" class="style12" colspan="2" style="text-align: center;">
                            <span class="style1"><span class="style13">**ติดต่อผู้พัฒนาระบบ วีระวัฒน์ 
                            วิไลศิริ (WRW) แผนก IS โทร.1256**</span></span></td>
                    </tr>
                </TABLE>
                <br />
                <table 
                    
                    style="width: 96%; height: 411px;">
                <tr>
                    <td class="style8">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style8">
                        &nbsp;</td>
                    <td>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                    </td>
                    <td>
                        &nbsp;</td>
                </tr>
                </table>
            </center>
            <center>&#160; </center>
            <p><font face="MS Sans Serif"></font></p>
            <center></center>
            <center><br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br>
                </br></center>
        </asp:Panel>
        &nbsp;</center>
    </form>
</body>
</html>
